// RATe RACE ticker data
// Source: Karpathy AI Jobs / BLS OOH “Digital AI Exposure” scores, 0–10 scale.
// The HTML converts raw exposure into a stock-style ticker move:
//   exposure >= 5  → red negative pressure, e.g. 9/10 becomes -0.900 ▼
//   exposure < 5   → green resilience, e.g. 2/10 becomes +0.800 ▲
// Keep this file next to index.html.

window.RATE_RACE_TICKER_JOBS = [
  { title: 'MEDICAL TRANSCRIPTIONISTS', exposure: 10 },
  { title: 'ROOFERS', exposure: 1 },
  { title: 'SOFTWARE DEVELOPERS', exposure: 9 },
  { title: 'ELECTRICIANS', exposure: 2 },
  { title: 'FINANCIAL ANALYSTS', exposure: 9 },
  { title: 'WELDERS', exposure: 2 },
  { title: 'MARKET RESEARCH ANALYSTS', exposure: 9 },
  { title: 'CONSTRUCTION LABORERS', exposure: 1 },
  { title: 'GRAPHIC DESIGNERS', exposure: 9 },
  { title: 'PLUMBERS', exposure: 2 },
  { title: 'DATA SCIENTISTS', exposure: 9 },
  { title: 'JANITORS', exposure: 1 },
  { title: 'CUSTOMER SERVICE REPS', exposure: 9 },
  { title: 'CARPENTERS', exposure: 2 },
  { title: 'BOOKKEEPING CLERKS', exposure: 9 },
  { title: 'GROUNDS MAINTENANCE', exposure: 1 },
  { title: 'PARALEGALS', exposure: 9 },
  { title: 'HVAC MECHANICS', exposure: 2 },
  { title: 'DATABASE ADMINISTRATORS', exposure: 9 },
  { title: 'AUTOMOTIVE MECHANICS', exposure: 3 },
  { title: 'WEB DEVELOPERS', exposure: 9 },
  { title: 'FIREFIGHTERS', exposure: 3 },
  { title: 'WRITERS AND AUTHORS', exposure: 9 },
  { title: 'BOILERMAKERS', exposure: 2 },
  { title: 'INTERPRETERS AND TRANSLATORS', exposure: 9 },
  { title: 'CONSTRUCTION EQUIPMENT OPS', exposure: 3 },
  { title: 'INSURANCE UNDERWRITERS', exposure: 9 },
  { title: 'DENTAL ASSISTANTS', exposure: 3 },
  { title: 'COURT REPORTERS', exposure: 9 },
  { title: 'WIND TURBINE TECHS', exposure: 2 },
  { title: 'INFORMATION SECURITY ANALYSTS', exposure: 8 },
  { title: 'COOKS', exposure: 3 },
  { title: 'ACCOUNTANTS AND AUDITORS', exposure: 8 },
  { title: 'IRONWORKERS', exposure: 1 },
  { title: 'MARKETING MANAGERS', exposure: 8 },
  { title: 'DELIVERY TRUCK DRIVERS', exposure: 3 },
  { title: 'ART DIRECTORS', exposure: 8 },
  { title: 'REGISTERED NURSES', exposure: 4 },
  { title: 'BUDGET ANALYSTS', exposure: 8 },
  { title: 'RETAIL SALES WORKERS', exposure: 4 },
  { title: 'COMPLIANCE OFFICERS', exposure: 8 },
  { title: 'POLICE AND DETECTIVES', exposure: 4 },
  { title: 'SECRETARIES AND ADMIN ASSISTANTS', exposure: 8 },
  { title: 'HEAVY VEHICLE TECHS', exposure: 3 },
  { title: 'ARCHITECTS', exposure: 7 },
  { title: 'WAITERS AND WAITRESSES', exposure: 3 },
  { title: 'FILM AND VIDEO EDITORS', exposure: 7 },
  { title: 'PHARMACY TECHNICIANS', exposure: 4 },
  { title: 'HIGH SCHOOL TEACHERS', exposure: 7 },
  { title: 'SOLAR PV INSTALLERS', exposure: 2 },
  { title: 'MANAGEMENT ANALYSTS', exposure: 7 },
  { title: 'BAKERS', exposure: 2 },
  { title: 'LOGISTICIANS', exposure: 7 },
  { title: 'BARTENDERS', exposure: 2 },
];